NET_INFO_PATH : ./data_config.yml
#Basic Path
DATASET_NAME : 128x128_FIX_NOPADDING_SEQ

TRAINING_ORG_PATH : [F:\UHD, F:\FHD]
TEST_ORG_PATH : [F:\ctc]
VALIDATION_ORG_PATH : [F:\UHD, F:\FHD]
DECODE_LOG_PATH : ./build_data/logs

TRAINING_BIN_PATH : [C:\Users\tuzm2\Desktop\ywkim\VTM6.1bin\FHD, C:\Users\tuzm2\Desktop\ywkim\VTM6.1bin\UHD]
TEST_BIN_PATH : [C:\Users\tuzm2\Desktop\VTM6.1bin\test]
VALIDATION_BIN_PATH : [C:\Users\tuzm2\Desktop\ywkim\VTM6.1bin\VALIDATION]

ADDITION_DATA : 1
IS_ONLY_ONE_INTRA : 0 #default zero, only use when you get png data
PNG_ORG_PATH : [C:/intra_additional/DIV2K_train_YUV]
TRAINING_PNG_PATH : [C:/Users/tuzm2/Desktop/VTM6.1bin/PNG_DATA/PNGDATA]
VALIDATION_PNG_PATH : [C:/Users/tuzm2/Desktop/VTM6.1bin/PNG_DATA/valid_bin]


#Dataset Path
DECODER_PATH : ./build_data/DecoderApp.exe
DATASET_PATH : ./Dataset
TRAININGSET_PATH : Training
VALIDATIONSET_PATH : Validation
TESTSET_PATH : Test
SAMPLE_IMAGE_PATH : ImageSample
TEMP_PATH : ./temp
CSV_NAME : block_info.csv


#Dataset Number
TARGET_DATASET_NUM : 200000 # Training + Validation Set
VALIDATION_DATSET_NUM : 30000
TARGET_TESTSET_NUM : 2 # [0 : All Frame, Others : A few frames ahead each Test Sequence]

#Dataset Shape Setting
USE_CONST_BLOCK : 1 # 0 : split by tu, 1 : split by const size
CONST_WIDTH : 128
CONST_HEIGHT : 128
SAVE_TU_CONST_BLOCK_INFO : 1 # 0 : Disable , 1 : Luma , 2 : Chroma, 3 : Dual
CONST_BLOCK_INTERVAL : 1
GET_TESTSET_BY_PICTURE : 1


#TU Size
IS_TU_SPLIT: 0 # [1 : split by tu luma], [2 : split by tu Chroma]
MIN_WIDTH_SIZE : 1
MAX_WIDTH_SIZE : 128
MIN_HEIGHT_SIZE : 1
MAX_HEIGHT_SIZE : 128
ONLY_SQUARE : 0 # [0 : Rectangle and Square], [1 : Square]

#Dataset Format Setting
#Data Order : [OriginalY -> OriginalCbCr -> PredY -> PredCbCr
#             -> FilteredReconY -> FilteredReconUV
#             -> UnfilteredReconY -> UnfilteredReconUV]
ONLY_LUMA : 0 # [1 : YCbCr], [0: Y]
PEL_DATA : [1, 1, 1, 1] # Origianal, Prediction, Reconstruction, UnfilteredRecon
#TU_MAP : [1, 1, 1] # Must Same Shape as TU_DATA_OTHERS


#Others Setting
SKIP_TU_DEPENDENT_QP : 0 # [0 : skip by binfile qp], [1: skip by tu dependent qp]
QP : [22, 27, 32, 37]
MODE : 1 # [0 : Intra&Inter], [1 : Only Intra], [2 : Only Inter]
INTRA_MODE : [] # if Empty, All mode
INTER_MODE : []
PARALLEL_DECODE : 10 # [1 : None parrallel processing], [Others : Thread number]
INTRA_TEMPORAL_SUBSAMPLE_RATIO : 8
DECODER_BIT_DEPTH : 10


CTU_DTA_OTHERS: ['ALFLUMA']
TU_DATA_OTHERS: ['QP', 'MODE', 'DEPTH', 'HOR_TR', 'VER_TR'] # data order [width, height, x_pos, y_pos, qp, ... etc]


#Padding Setting
LUMA_PAD : [0,0,0,0] # [0 : None], [others : size] # [up, down, left, right]
CHROMA_PAD : [0,0,0,0] # [0 : None], [others : size]
PIC_BOUNDARY_PAD : 0 # [-1 : minus one], [0 : Zeros], [1 : Same], [2 : without boundary block]


#Compensate Dataset Probabilty
OPT : 1 # [0: Random], [1: Compensate Block Area],
        #[2: Compensate Block Error by MSE]
        #[3: Compensate Block Error by Squared Error]
COMPARE_OPT : 3 # [1: Prediction],
                #[2: Reconstruction],
                #[3: Unfiltered] # Only 'OPT' option is 2 or 3
YUV_OPT : 0 # [0: YUV] , [1:Y], [2: UV] # Only 'OPT' option is 2 or 3

